Algoritmo "ImprimindoFor1a10"
// Disciplina   : [Lógica de Programação]
// Professor   : Marcos Monteiro
// Descrição   : Imprimindo os números de 1 a 10, em ordem crescente
//Descrição    : utilizando a estrutura para (for), encrementando
//Descrição    : o valor inicial da variável "J"
// Autor(a)    : Marcos Franco
// Data atual  : 11/02/2023

Var
   j: inteiro

Inicio
   escreval("Imprimindo de 1 a 10:")
   para j de 1 ate 10 faca
     escreval(j)
   fimpara
   
Fimalgoritmo