Algoritmo "NotasAluno"
// Disciplina   : [Lógica de Programação]
// Professor   : Marcos Monteiro
// Descrição   : Armazena as notas dos alunos
// em seguida exibe a média das notas de cada aluno(a).
// Autor(a)    : Marcos Franco
// Data atual  : 11/02/2023
Var nota1, nota2: REAL;

Inicio
   escreva("Digite a 1ª nota:")
   leia(nota1)
   escreva("Digite a 2ª nota:")
   leia(nota2)
   escreva("Média obtida:", ((nota1+nota2)/2))
   
Fimalgoritmo